package fr.jlisp.lexical;

public enum Type {

	BLANK,
	NEW_LINE,
	IDENTIFIER,
	NULL_KEYWORD,
	TRUE_KEYWORD,
	FALSE_KEYWORD,
	INTEGER_LITERAL,
	FLOAT_LITERAL,
	STRING_LITERAL,
	CHAR_LITERAL,
	START_DELIMITER,
	END_DELIMITER
}